name: React build
on:
  push:
    branches:
      - feature/bongbong/codedeploy-2

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code. # 레포지토리 체크아웃
        uses: actions/checkout@v1
      - name: Cache node modules # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # React Build
        run: npm run build
        env:
          CI: ""

      - name: zip create
        run: zip -qq -r ./build-fe.zip
        shell: bash

      - name: Deploy # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://bongbong-github-actions-tutorial/build-fe.zip
      -name: Deploy 
        run: aws deploy create-deployment
          --aplication-name bongbong-practice
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name bongbong-deploy-groupName
          --s3-location bucket=bongbong-github-actions-tutorial,key=/build-fe.zip,bundleType=zip
            
