name: Deploy
on:
  push:
    branches:
      - feature/bongbong/codedelpoy-1
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2
      - name: Check Node v
        run: node -v
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: zip create
        run: zip -qq -r ./build-fe.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIA4ZD4GKWXI32YJEZD
          aws-secret-access-key: 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
          aws-region: ap-northeast-2
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: AKIA4ZD4GKWXI32YJEZD
          AWS_SECRET_ACCESS_KEY: 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
        run: |
          aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://bongbong.practice.co.kr/deployTest//build-fe.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name bongbong-practice
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name bongbong-deploy-groupName
          --s3-location bucket=bongbong.practice.co.kr,key=deployTest/build-fe.zip,bundleType=zip
